### ISSUE TITLE
fitHiChip into nextflow nf-core/hic 

### ISSUE THREAD

**Issue by tiagochst** [ay-lab/FitHiChIP#15]
Hello, 

I am new to hi-c analysis/available tools/pipelines. So I might be asking a stupid question.

But the nf-core has a pipeline for the HI-C nextflow analysis using the HiC-Pro
https://github.com/nf-core/hic. And I understand fitHiChip should be used after HiC-Pro.

Is there any plan to integrate fitHiChip into the nf-core/hic ?
I saw this repository has some nextflow files, but I am not sure if it is integrated with  nf-core/hic or if they don't have any relationship. 

Otherwise, the nextflow here works with the output from the nf-core/hic one?

Thanks!

**Comment by tuvangezer** [comment]
Hello,
We are currently in the process of implementing containerized options for running FitHiChIP. 
Thank you for suggesting adding it to the nf pipeline repos, we will look into it. The current nextflow files in the repo are just for easing the docker process and they are not to be executed directly, they are meant to be used with the wrapper script (FitHiChIP_Docker.sh)
We don’t have documentation yet since they are not finalized and might be problematic for certain inputs. 

As for using FitHiChIP, there are extensive instructions with examples on https://ay-lab.github.io/FitHiChIP  You can generate a FitHiChIP configuration from the HiCPro output and use the nextflow file. (Though since it is not yet completely finished, currently it only works with the docker profile chosen, and might produce errors with some options.)
