### ISSUE TITLE
input for —ChIPAlignFileList flag 

### ISSUE THREAD

**Issue by hhhcce** [ay-lab/FitHiChIP#17]
I was wondering what should be the input bam for differential analysis because there are three different bam files from HiC-Pro (bwt2, bwt2_glob, bwt2_local)?

**Comment by hhhcce** [comment]
I only did HiChIP for H3K27ac and hic_pro gave three files (bwt2, bwt2_glob, bwt2_local). All three files are quite big so when I ran Differetial_Analysis_Script.sh using bwts file from HiC-Pro,  the program consistently ran out of memory (64GB). Let me know if I am using the right file. Thanks!

**Comment by jonasungerback** [comment]
Hello,

I have a (potentially) related problem and will therefore continue in this thread instead of open a new. If that is inappropriate, please let me know and I can open a new Issue. Brief explanation: I have no replicates at the moment but I want to compare two conditions. The input files I use are the full interaction files per condition and for `--ChIPAlignFileList` I use two standard bam-files for my ChIP-sample that have been aligned with bowtie2 and sorted and indexed with samtools. However, early in the process I get the following error that I fail to troubleshoot:

#############################################################
===>> Merging ChIP coverage - processing ChIP-seq alignment file : /path-to-files//WT_rep1_2.s.bam ====>> 

 ===>> Merging ChIP coverage - processing ChIP-seq alignment file : path-to-files//EKO_rep1_2.s.bam  ====>> 
Killed

 ===>> Scaling ChIP coverage - scaling_factor : NA ====>> 
rm: cannot remove './/ChIP_Coverage_temp2.bed': No such file or directory

 *** Performed scaling of ChIP coverage values for uniform ChIP coverage *** 

 ===>>> GroupDistrVec : WT	  
 ===>>> GroupDistrVec : EKO	 Error in DGEList(counts = CountData, group = GroupDistrVec) : 
  The count matrix is a data.frame instead of a matrix and the first 2 columns are non-numeric.
Should these columns be entered as annotation instead of as counts?
Calls: ApplyEdgeR -> DGEList
Execution halted`
###########################################################

This is the command I am using:

`Rscript /path-to-FitHiChIP/DiffAnalysisHiChIP.r --AllLoopList /path-to-interaction-file_1/FitHiChIP_Peak2ALL_b5000_L10000_U3000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/WT_5kb.interactions_FitHiC.bed,/path-to-interaction-file_2/FitHiChIP_Peak2ALL_b5000_L10000_U3000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/EKO.interactions_FitHiC.bed --ChrSizeFile /path-chrom-size-file/mm10_chrNameLength.txt --FDRThr 0.05 --OutDir ./ --ChIPAlignFileList  /path-to-bam-files/WT_rep1_2.s.bam, /path-to-bam-files/EKO_rep1_2.s.bam --CategoryList WT,EKO`

Thank you in advance!

Jonas

**Comment by ay-lab** [comment]
Hi, 
Thanks for your query. The _--ChIPAlignFileList_ option corresponds to ChIP-seq alignment files, not the HiChIP alignment files. So, you have to use a H3K27ac ChIP-seq alignment data corresponding to your HiChIP data cell types. You may download reference ChIP-seq data from ENCODE and use them. Note that two different ChIP-seq data files are required corresponding to two different categories of HiChIP data you are experimenting with. 
Hope this helps. Please reply in case of any problems.
