### ISSUE TITLE
Peak to peak background spline fit, model fails with NaNs error

### ISSUE THREAD

**Issue by DoaneAS** [ay-lab/FitHiChIP#4]
Hi,
Thanks for FitHiChIP.  I'm seeing an error in the P2P background model fitting:
```
Peak to peak background usage for spline fit: 1
 Number of cores in the system: 56
 Total Number of interactions: 6429386
 ****** Total number of training interactions: 611127 ********
 ****** Number of contacts per bin (allowed for equal occupancy binning): 13205 ********

 modeled fit_spline_coeff_Intercept
 modeled fit_spline_coeff_Logbias1
 modeled fit_spline_coeff_Logbias2Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NaNs produced
2: In xy.coords(x, y) : NaNs produced
3: NAs introduced by coercion to integer range
******** FINISHED calling significant interactions
----- Extracted significant interactions ---- FDR threshold lower than: 0.01
There is no significant interaction - so no WashU specific session file is created !!
Updated CurrIntType: 4

 **** Now summarizing FitHiChIP results in the HTML file ***

***** FitHiChIP pipeline is completely executed - congratulations !!! *****
```

I've tried with ICE bias and Coverage.  The data is H3K27ac HiChIP in a cell line and I'm using ENCODE ChIP-seq peaks (same cell line, OCI-LY7).  HICCUPS calls ~4000 loops.  Do you have any suggestions for debugging this?
thanks!
Ashley

**Comment by ay-lab** [comment]
HI Ashley,

Thanks for your feedback. Just to confirm, did you get this error for both coverage or ICE bias? Or is it specific to ICE bias?
ICE bias and matrix balancing may sometimes produce very high bias values, even for low coverage regions, resulting number overflow (NaN's). I've fixed the issue for ICE bias. Please update the file  
"src/FitHiC_SigInt.r" with the latest code, and check if the error is solved. Otherwise, please inform us.
