### ISSUE TITLE
only merged the chr1, here should add a for in loop

### ISSUE THREAD

**Issue by xubeisi** [ay-lab/FitHiChIP#47]
https://github.com/ay-lab/FitHiChIP/blob/fd6d4ddbc1eb4ff38c2d985303e984e9c2aa49bd/src/CombineNearbyInteraction.py#L196

**Comment by jonasungerback** [comment]
Hello,

I see a similar problem after updating to version 8.1 so instead of opening a new Issue I add to this. I have a PLAC-seq dataset where I with v. 8.0 and v 8.1 identify 173465 interactions pre-merging but post-merging/combining, these numbers are 89808 and 4731 interactions, respectively, which of course is a huge difference and what I assume is a bug related to the title of this Issue?

Jonas

**Comment by xubeisi** [comment]
@jonasungerback probably, check the merged file, if they are all chr1, then the reference line in this script is the reason.

> Hello,
> 
> I see a similar problem after updating to version 8.1 so instead of opening a new Issue I add to this. I have a PLAC-seq dataset where I with v. 8.0 and v 8.1 identify 173465 interactions pre-merging but post-merging/combining, these numbers are 89808 and 4731 interactions, respectively, which of course is a huge difference and what I assume is a bug related to the title of this Issue?
> 
> Jonas

**Comment by ay-lab** [comment]
Hi @xubeisi and @jonasungerback 
Many thanks for pointing out the issue. I have modified the code. Please download the updated file "src/CombineNearbyInteraction.py" or git clone the modified repository. Please let me know for any issues.

**Comment by jonasungerback** [comment]
Looks like it is working smoothly now. Thank you!
